spring.application.name=auth-service

server.port=${PORT:8081}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=${EUREKA_URL:https://hireconnect-eureka-service.onrender.com/eureka}
eureka.instance.prefer-ip-address=true
eureka.client.registry-fetch-interval-seconds=10

app.oauth2.redirect-success-url=${OAUTH2_REDIRECT_SUCCESS_URL:http://localhost:4200/oauth/callback}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI:${API_GATEWAY_URL:http://localhost:8080}/login/oauth2/code/google}

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.registration.github.redirect-uri=${GITHUB_REDIRECT_URI:${API_GATEWAY_URL:http://localhost:8080}/login/oauth2/code/github}

spring.data.redis.host=${REDIS_HOST:localhost}


spring.data.redis.port=${REDIS_PORT:6379}
