spring.application.name=notification-service

server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/notification_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ankits6387@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=ankits6387@gmail.com
spring.mail.password=finsopufebekmarc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.rabbitmq.exchange=hireconnect.notifications.exchange
app.rabbitmq.notification-queue=hireconnect.notifications.queue
app.rabbitmq.notification-routing-key=notification.send
app.rabbitmq.dead-letter-queue=hireconnect.notifications.dlq
app.rabbitmq.dead-letter-routing-key=notification.dead
