spring.application.name=application-service

server.port=${PORT:8084}

# MySQL Config
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/jobservice_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Ankits6387@}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=${EUREKA_URL:https://hireconnect-eureka-service.onrender.com/eureka}
eureka.instance.prefer-ip-address=true
eureka.client.registry-fetch-interval-seconds=10
