spring.application.name=subscription-service

server.port=8087

spring.datasource.url=jdbc:mysql://localhost:3306/subscription_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ankits6387@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

razorpay.key=rzp_test_SirlxvTw5D0T5m
razorpay.secret=24geZyPyudB2zKsAdr1oYEK4
