spring.application.name=subscription-service

server.port=${PORT:8087}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=${EUREKA_URL:https://hireconnect-eureka-service.onrender.com/eureka}
eureka.instance.prefer-ip-address=true
eureka.client.registry-fetch-interval-seconds=10

razorpay.key=${RAZORPAY_KEY:rzp_test_SirlxvTw5D0T5m}
razorpay.secret=${RAZORPAY_SECRET:24geZyPyudB2zKsAdr1oYEK4}
