spring.application.name=user-service

server.port=${PORT:8082}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=${EUREKA_URL:https://hireconnect-eureka-service.onrender.com/eureka}
eureka.instance.prefer-ip-address=true
eureka.client.registry-fetch-interval-seconds=10
