spring.application.name=analytics-service

server.port=${PORT:8088}

eureka.client.service-url.defaultZone=${EUREKA_URL:https://hireconnect-eureka-service.onrender.com/eureka}
eureka.instance.prefer-ip-address=true
eureka.client.registry-fetch-interval-seconds=10
