spring.application.name=eureka-service

server.port=${PORT:8761}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.instance.hostname=hireconnect-eureka-service.onrender.com

eureka.client.service-url.defaultZone=https://hireconnect-eureka-service.onrender.com/eureka/

eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000